name: Java CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'   # or 11, depending on your project
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test
