name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99    

      - name: Build with Maven
        run: mvn clean test -Dusername=${{ secrets.MY_USERNAME }} -Dpassword=${{ secrets.MY_PASSWORD }}
        env:
          Display: :99
